###### good version
#version : '3'
#
#services:
#  mysql:
#    image: mysql:latest
##    container_name: dev_mysql
#    environment:
#      MYSQL_USER: user
#      MYSQL_PASSWORD: user
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: default_schema
#
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
##    container_name: dev_pma
#    links:
#      - mysql
#    environment:
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#      PMA_ARBITRARY: 1
#    restart: always
#    ports:
#      - 8183:80
#version : '3'
#
#services:
#  db:
#    image: postgres:latest
#    container_name: dev_postgres
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: user
#      restart: always
#  phppgadmin:
#    image: einfallstoll/phppgadmin
#    links:
#      - db
#    restart: always
#    environment: 
#      POSTGRES_DEFAULTUSER: someuser
#      POSTRGES_DEFAULTPASSWORD: somepassword
#      POSTGRES_HOST: db
#    ports:
#      - 8000:80


###### good version
version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    restart: always
    ports:
      - 5432:5432
  phppgadmin:
    image: dockage/phppgadmin
    environment:   
      PHP_PG_ADMIN_SERVER_HOST: db
    links:
      - db
    ports:
      - 8000:80  
    restart: always        
  






#version : '3'
#
#services:
#  pgAdmin:
#    restart: always
#    image: dpage/pgadmin4
#    ports:
#      - 8000:80
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin
#      PGADMIN_DEFAULT_PASSWORD: admin
#  postgres:
#    restart: always
#    image: postgres
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: a
#      POSTGRES_PASSWORD: a
